# Generated by Django 3.0.4 on 2020-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCases',
            fields=[
                ('country', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('total_cases', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('new_cases', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('total_deaths', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('new_deaths', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('total_recovered', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('active_cases', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('serious_critical', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('cases_per_mill_pop', models.FloatField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralStats',
            fields=[
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('total_cases', models.BigIntegerField(db_index=True)),
                ('death_cases', models.BigIntegerField(db_index=True)),
                ('recovery_cases', models.BigIntegerField(db_index=True)),
                ('currently_infected', models.BigIntegerField(db_index=True)),
                ('cases_with_outcome', models.BigIntegerField(db_index=True)),
                ('mild_condition_active_cases', models.BigIntegerField(db_index=True)),
                ('critical_condition_active_cases', models.BigIntegerField(db_index=True)),
                ('recovered_closed_cases', models.BigIntegerField(db_index=True)),
                ('death_closed_cases', models.BigIntegerField(db_index=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
