# Generated by Django 3.0.4 on 2020-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycases',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
