# Generated by Django 3.0.4 on 2020-03-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_countrycases_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycases',
            old_name='code',
            new_name='flag',
        ),
    ]
