# Generated by Django 3.0.4 on 2020-03-29 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20200315_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrycases',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
