# Generated by Django 3.0.4 on 2020-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_countrycases_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrycases',
            name='total_recovered',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
